package com.yuvalitzchakov.asyncpc

import cats.effect.Effect

import scala.sys.process.Process

object EventSource {

  /**
    * Created an event source which reads STDOUT lines from the underlying data generator process
    * @param generatorPath The path to the data generator executable
    * @return An fs2.Stream of lines generated by the process
    */
  def standardInputSource[F[_]](generatorPath: String)(implicit E: Effect[F]): SourceValue[F] =
    fs2.Stream.fromIterator[F, String](Process(generatorPath).lineStream_!.iterator)
}
