package com.yuvalitzchakov.asyncpc

import cats.effect.Effect

import scala.sys.process.Process

object EventSource {

  /**
    * Creates an event source which reads STDOUT string lines from the underlying data generator process
    * @param generatorPath The path to the data generator executable
    * @return An fs2.Stream of lines generated by the process
    */
  def standardInputSource[F[_]](generatorPath: String)(
      implicit E: Effect[F]): fs2.Stream[F, String] =
    fs2.Stream.fromIterator[F, String](Process(generatorPath).lineStream_!.iterator)
}
